spring:
  application:
    name: WeatherApp
  datasource:
    url: jdbc:postgresql://postgres-db:5433/WeatherAppDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 171101
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml
